CREATE TABLE error_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    error_message TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL,
    error_code INT NULL,
    error_file VARCHAR(255) NULL,
    error_line INT NULL,
    error_trace TEXT NULL,
    request_method VARCHAR(10) NULL,
    request_uri TEXT NULL,
    request_headers TEXT NULL,
    request_body TEXT NULL,
    user_id BIGINT UNSIGNED NULL,
    user_ip VARCHAR(45) NULL,
    user_agent TEXT NULL,
    server_name VARCHAR(255) NULL,
    server_port INT NULL,
    server_protocol VARCHAR(10) NULL,
    server_software VARCHAR(255) NULL,
    environment VARCHAR(20) NULL,
    email VARCHAR(255) NULL,
    log_time TIME NULL,
    log_date DATE NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);